title: Juan Manuel CABRERA RODRÍGUEZ \n Data Scientis
title2: Data Scientist
logo: /assets/img/22642850.png
description: Personal Portfolio.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
